export default {
  // categories
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CATEGORIES_COMPLETED: 'FETCH_CATEGORIES_COMPLETED',

  // posts
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_COMPLETED: 'FETCH_POSTS_COMPLETED',
  ADD_NEW_POST: 'ADD_NEW_POST',
  ADD_NEW_POST_COMPLETED: 'ADD_NEW_POST_COMPLETED',
  EDIT_POST: 'EDIT_POST',
  EDIT_POST_COMPLETED: 'EDIT_POST_COMPLETED',
  DELETE_POST: 'DELETE_POST',
  DELETE_POST_COMPLETED: 'DELETE_POST_COMPLETED',

  // comments
  FETCH_POST_COMMENTS: 'FETCH_POST_COMMENTS',
  FETCH_POST_COMMENTS_COMPLETED: 'FETCH_POST_COMMENTS_COMPLETED',
  ADD_NEW_COMMENT: 'ADD_NEW_COMMENT',
  ADD_NEW_COMMENT_COMPLETED: 'ADD_NEW_COMMENT_COMPLETED',
  EDIT_COMMENT: 'EDIT_COMMENT',
  EDIT_COMMENT_COMPLETED: 'EDIT_COMMENT_COMPLETED',
  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_COMMENT_COMPLETED: 'DELETE_COMMENT_COMPLETED',
};
